# Generated by Django 5.1.2 on 2024-11-06 07:28

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "catagories",
                "db_table": "menu_categories ",
                "ordering": ["title"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("menu-categories"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
                ),
                ("featured", models.BooleanField(db_index=True, default=False)),
                ("calories", models.IntegerField(blank=True, null=True)),
                (
                    "sugar_gm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "protien_gm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "carbohydrates_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "saturated_fat_gm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("contains_dairy", models.BooleanField(blank=True, null=True)),
                ("contains_treenuts", models.BooleanField(blank=True, null=True)),
                ("contains_gluten", models.BooleanField(blank=True, null=True)),
                ("is_on_sale", models.BooleanField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="LittleLemonAPI.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
                "db_table": "menu_items",
                "ordering": ["category", "title"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("menu_items"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(db_index=True, default=0)),
                ("total", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField(auto_now=True, db_index=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "delivery_crew",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_crew",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "db_table": "orders",
                "ordering": ["user", "date", "status"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("orders"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.SmallIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menuitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="LittleLemonAPI.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
                "db_table": "user_carts",
                "ordering": ["user"],
                "unique_together": {("menuitem", "user")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("carts"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("order_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.SmallIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "menuitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LittleLemonAPI.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LittleLemonAPI.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
                "db_table": "order_items",
                "ordering": ["order"],
                "unique_together": {("order", "menuitem")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("order-items"),
                models.Model,
            ),
        ),
    ]
