# Generated by Django 5.1.2 on 2024-11-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="calories",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="carbohydrates_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="contains_dairy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="contains_gluten",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="contains_treenuts",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="protien_gm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="saturated_fat_gm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="sugar_gm",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
    ]
