# Generated by Django 5.1.2 on 2024-11-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="protien_gm",
            new_name="protein_gm",
        ),
    ]
