# Generated by Django 5.1.2 on 2024-11-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_menuitem_calories_menuitem_carbohydrates_mg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="calories",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
