# Generated by Django 5.1.2 on 2024-11-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0003_alter_menuitem_calories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="carbohydrates_mg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="protien_gm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="saturated_fat_gm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="sugar_gm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
